# Generated by Django 5.1.15 on 2026-05-23 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TouristTaxAccommodationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'tourist tax accommodation categories',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TouristTaxOrdinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TouristTaxSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64)),
                ('kind', models.CharField(choices=[('main', 'Glavna sezona'), ('off', 'Izvan sezone')], max_length=16)),
                ('start_month', models.PositiveSmallIntegerField()),
                ('start_day', models.PositiveSmallIntegerField()),
                ('end_month', models.PositiveSmallIntegerField()),
                ('end_day', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordinance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='tourist_tax.touristtaxordinance')),
            ],
            options={
                'ordering': ['ordinance_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TouristTaxZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('central', 'Uže gradsko jezgro / turistička naselja'), ('peripheral', 'Okolna naselja (zaleđe)')], max_length=32)),
                ('settlements', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordinance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='tourist_tax.touristtaxordinance')),
            ],
            options={
                'ordering': ['ordinance_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TouristTaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='tourist_tax.touristtaxaccommodationcategory')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='tourist_tax.touristtaxseason')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='tourist_tax.touristtaxzone')),
            ],
            options={
                'ordering': ['zone_id', 'season_id', 'category_id'],
            },
        ),
        migrations.CreateModel(
            name='TouristTaxAgeBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64)),
                ('min_age', models.PositiveSmallIntegerField()),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordinance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_brackets', to='tourist_tax.touristtaxordinance')),
            ],
            options={
                'ordering': ['ordinance_id', 'sort_order', 'min_age'],
                'constraints': [models.UniqueConstraint(fields=('ordinance', 'code'), name='tourist_tax_age_bracket_unique_ordinance_code')],
            },
        ),
        migrations.AddConstraint(
            model_name='touristtaxseason',
            constraint=models.UniqueConstraint(fields=('ordinance', 'code'), name='tourist_tax_season_unique_ordinance_code'),
        ),
        migrations.AddConstraint(
            model_name='touristtaxzone',
            constraint=models.UniqueConstraint(fields=('ordinance', 'code'), name='tourist_tax_zone_unique_ordinance_code'),
        ),
        migrations.AddConstraint(
            model_name='touristtaxrate',
            constraint=models.UniqueConstraint(fields=('zone', 'season', 'category'), name='tourist_tax_rate_unique_zone_season_category'),
        ),
    ]
