# Generated by Django 5.1.15 on 2026-05-27 04:12

import apps.billing.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0011_remove_smoobu'),
        ('tenants', '0012_remove_smoobu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=64)),
                ('sequence_number', models.PositiveIntegerField()),
                ('issued_at', models.DateTimeField()),
                ('buyer_name', models.CharField(max_length=255)),
                ('payment_method', models.CharField(choices=[('booking', 'Booking'), ('cash', 'Cash'), ('card', 'Card'), ('transfer', 'Transfer'), ('other', 'Other')], default='other', max_length=16)),
                ('payment_note', models.TextField(blank=True, default='')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('zki', models.CharField(blank=True, default='', max_length=32)),
                ('jir', models.CharField(blank=True, default='', max_length=36)),
                ('fiscal_status', models.CharField(choices=[('pending', 'Pending'), ('fiscalized', 'Fiscalized'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('fiscal_error', models.TextField(blank=True, default='')),
                ('fiscalized_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=apps.billing.models.invoice_pdf_upload_to)),
                ('public_access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_recipient', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='reservations.reservation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-issued_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FiscalizationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveSmallIntegerField()),
                ('success', models.BooleanField(default=False)),
                ('request_snapshot', models.TextField(blank=True, default='')),
                ('response_snapshot', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscalization_attempts', to='billing.invoice')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('line_kind', models.CharField(choices=[('accommodation', 'Accommodation'), ('tourist_tax_adult', 'Tourist tax — adults'), ('tourist_tax_child', 'Tourist tax — children')], max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TenantFiscalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_vat_registered', models.BooleanField(default=False, help_text='Tenant is in the Croatian VAT system and must issue fiscalized guest invoices.')),
                ('issuer_oib', models.CharField(blank=True, default='', max_length=11)),
                ('issuer_name', models.CharField(blank=True, default='', max_length=255)),
                ('issuer_address', models.TextField(blank=True, default='')),
                ('issuer_iban', models.CharField(blank=True, default='', max_length=34)),
                ('business_premise_code', models.CharField(blank=True, default='', max_length=20)),
                ('payment_device_code', models.CharField(blank=True, default='', max_length=20)),
                ('operator_code', models.CharField(blank=True, default='', help_text='Operator mark on fiscal device (e.g. OIB-1).', max_length=64)),
                ('accommodation_vat_rate', models.DecimalField(decimal_places=2, default=Decimal('13.00'), max_digits=5)),
                ('invoice_sequence', models.PositiveIntegerField(default=0)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to=apps.billing.models.fiscal_certificate_upload_to)),
                ('certificate_password_encrypted', models.TextField(blank=True, default='')),
                ('certificate_expires_at', models.DateField(blank=True, null=True)),
                ('use_test_endpoint', models.BooleanField(default=True, help_text='Use CIS test endpoint (cistest.apis-it.hr).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_settings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant fiscal settings',
                'verbose_name_plural': 'Tenant fiscal settings',
            },
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('tenant', 'sequence_number'), name='billing_invoice_unique_tenant_sequence'),
        ),
        migrations.AddConstraint(
            model_name='fiscalizationattempt',
            constraint=models.UniqueConstraint(fields=('invoice', 'attempt_no'), name='billing_fiscal_attempt_unique_invoice_attempt'),
        ),
    ]
