# Generated by Django 5.1.15 on 2026-05-23 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_unit_bathroom'),
        ('tourist_tax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='tourist_tax_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='tourist_tax.touristtaxaccommodationcategory'),
        ),
        migrations.AddField(
            model_name='property',
            name='tourist_tax_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='tourist_tax.touristtaxzone'),
        ),
    ]
