# Generated by Django 5.1.15 on 2026-05-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_integrationconfig_config_encrypted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationconfig',
            options={'ordering': ['provider', 'property_id']},
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Legacy/plaintext fallback; novi zapisi koriste config_encrypted.'),
        ),
    ]
