# Generated by Django 5.1.15 on 2026-05-20 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_unitrateday'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='channexarioutbox',
            new_name='integration_tenant__0e529e_idx',
            old_name='integration_tenant__a8f1c2_idx',
        ),
        migrations.RenameIndex(
            model_name='rateplanday',
            new_name='integration_tenant__0c2284_idx',
            old_name='integration_tenant__b3e4d1_idx',
        ),
        migrations.RenameIndex(
            model_name='unitavailabilityday',
            new_name='integration_tenant__d2cb42_idx',
            old_name='integration_tenant__c5f6a7_idx',
        ),
        migrations.RenameIndex(
            model_name='unitrateday',
            new_name='integration_tenant__d428a3_idx',
            old_name='integration_tenant__d7e8f9_idx',
        ),
    ]
