# Generated by Django 5.1.15 on 2026-05-23 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0014_whatsapp_integration'),
        ('tenants', '0009_tenantreceptionsettings_guest_smtp_password'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='unitavailabilityblock',
            new_name='integration_tenant__041bb0_idx',
            old_name='integration_tenant__4b8e2a_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappmessage',
            new_name='integration_tenant__f5756a_idx',
            old_name='integration_tenant__wa_msg_idx',
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
    ]
