# Generated by Django 5.1 on 2026-05-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_unit_bed"),
        ("tenants", "0005_tenantreceptionsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantdomain",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tenant_domains",
                to="properties.property",
            ),
        ),
    ]
