from django.urls import path

from apps.api.reception_availability_views import ReceptionUnitAvailabilityView
from apps.api.reception_calendar_block_views import (
    ReceptionCalendarBlocksView,
    ReceptionUnitBlockCreateView,
    ReceptionUnitBlockDeleteView,
)
from apps.api.reception_channex_views import (
    ReceptionChannelAvailabilityView,
    ReceptionChannelBulkApplyView,
    ReceptionChannelCalendarAriView,
    ReceptionChannelFullSyncView,
    ReceptionChannelRatePlansView,
    ReceptionChannelRatesView,
    ReceptionChannelStatusView,
    ReceptionReservationChannexMessagesView,
    ReceptionReservationCreateView,
)
from apps.api.billing_views import (
    InvoicePdfView,
    ReservationInvoicePdfView,
    ReservationInvoiceSendEmailView,
    ReservationInvoiceView,
)
from apps.api.reception_guest_messages_views import (
    ReceptionGuestMessageComposeView,
    ReceptionGuestMessageChannelsView,
    ReceptionGuestMessageDismissReplyView,
    ReceptionGuestMessageSendImageView,
    ReceptionGuestMessageSendView,
    ReceptionGuestMessageTranslateView,
    ReceptionGuestMessagesView,
    GuestOutboundMessageMediaView,
    WhatsAppMessageMediaView,
)
from apps.api.reception_message_threads_views import ReceptionMessageThreadsListView
from apps.api.reception_reviews_views import (
    ReceptionReservationReviewsView,
    ReceptionReviewComposeReplyView,
    ReceptionReviewDetailView,
    ReceptionReviewGuestReviewView,
    ReceptionReviewReplyView,
    ReceptionReviewsListView,
)
from apps.api.reception_document_intake_views import (
    DocumentIntakeBatchView,
    DocumentIntakeJobApplyView,
    DocumentIntakeJobDetailView,
    DocumentIntakeJobImageView,
    DocumentIntakeJobProcessView,
)
from apps.api.reception_views import (
    BookingPdfImportView,
    DocumentPhotosUploadView,
    DocumentScanIngestView,
    EvisitorSubmitView,
    GuestFacePhotoView,
    IdScanSampleUploadView,
    ReceptionHealthView,
    ReceptionMonthlyStatisticsView,
    ReceptionSyncVersionsView,
    ReservationConfirmationPdfView,
    ReservationDetailView,
    ReservationGuestDetailView,
    ReservationGuestListCreateView,
    ReservationTimelineListView,
)

urlpatterns = [
    path(
        "document-intake/batch/",
        DocumentIntakeBatchView.as_view(),
        name="reception-document-intake-batch",
    ),
    path(
        "document-intake/jobs/<int:job_id>/process/",
        DocumentIntakeJobProcessView.as_view(),
        name="reception-document-intake-process",
    ),
    path(
        "document-intake/jobs/<int:job_id>/",
        DocumentIntakeJobDetailView.as_view(),
        name="reception-document-intake-detail",
    ),
    path(
        "document-intake/jobs/<int:job_id>/images/<int:index>/",
        DocumentIntakeJobImageView.as_view(),
        name="reception-document-intake-image",
    ),
    path(
        "document-intake/jobs/<int:job_id>/apply/",
        DocumentIntakeJobApplyView.as_view(),
        name="reception-document-intake-apply",
    ),
    path("health/", ReceptionHealthView.as_view(), name="reception-health"),
    path(
        "sync-versions/",
        ReceptionSyncVersionsView.as_view(),
        name="reception-sync-versions",
    ),
    path(
        "statistics/monthly/",
        ReceptionMonthlyStatisticsView.as_view(),
        name="reception-statistics-monthly",
    ),
    path(
        "reservations/",
        ReservationTimelineListView.as_view(),
        name="reception-reservations-list",
    ),
    path(
        "reservations/create/",
        ReceptionReservationCreateView.as_view(),
        name="reception-reservation-create",
    ),
    path(
        "reservations/import-pdf/",
        BookingPdfImportView.as_view(),
        name="reception-reservation-import-pdf",
    ),
    path(
        "reservations/<int:pk>/confirmation-pdf/",
        ReservationConfirmationPdfView.as_view(),
        name="reception-reservation-confirmation-pdf",
    ),
    path(
        "reservations/<int:pk>/invoice/",
        ReservationInvoiceView.as_view(),
        name="reception-reservation-invoice",
    ),
    path(
        "reservations/<int:pk>/invoice/pdf/",
        ReservationInvoicePdfView.as_view(),
        name="reception-reservation-invoice-pdf",
    ),
    path(
        "reservations/<int:pk>/invoice/send-email/",
        ReservationInvoiceSendEmailView.as_view(),
        name="reception-reservation-invoice-send-email",
    ),
    path(
        "invoices/<int:invoice_id>/pdf/",
        InvoicePdfView.as_view(),
        name="reception-invoice-pdf",
    ),
    path(
        "reservations/<int:pk>/",
        ReservationDetailView.as_view(),
        name="reception-reservation-detail",
    ),
    path(
        "reservations/<int:reservation_id>/channex-messages/",
        ReceptionReservationChannexMessagesView.as_view(),
        name="reception-reservation-channex-messages",
    ),
    path(
        "reservations/<int:reservation_id>/messages/",
        ReceptionGuestMessagesView.as_view(),
        name="reception-reservation-messages",
    ),
    path(
        "reservations/<int:reservation_id>/messages/compose/",
        ReceptionGuestMessageComposeView.as_view(),
        name="reception-reservation-messages-compose",
    ),
    path(
        "reservations/<int:reservation_id>/messages/channels/",
        ReceptionGuestMessageChannelsView.as_view(),
        name="reception-reservation-messages-channels",
    ),
    path(
        "reservations/<int:reservation_id>/messages/send/",
        ReceptionGuestMessageSendView.as_view(),
        name="reception-reservation-messages-send",
    ),
    path(
        "reservations/<int:reservation_id>/messages/send-image/",
        ReceptionGuestMessageSendImageView.as_view(),
        name="reception-reservation-messages-send-image",
    ),
    path(
        "whatsapp-messages/<int:message_id>/media/",
        WhatsAppMessageMediaView.as_view(),
        name="reception-whatsapp-message-media",
    ),
    path(
        "guest-outbound-messages/<int:message_id>/media/",
        GuestOutboundMessageMediaView.as_view(),
        name="reception-guest-outbound-message-media",
    ),
    path(
        "reservations/<int:reservation_id>/messages/dismiss-reply/",
        ReceptionGuestMessageDismissReplyView.as_view(),
        name="reception-reservation-messages-dismiss-reply",
    ),
    path(
        "reservations/<int:reservation_id>/messages/translate/",
        ReceptionGuestMessageTranslateView.as_view(),
        name="reception-reservation-messages-translate",
    ),
    path(
        "message-threads/",
        ReceptionMessageThreadsListView.as_view(),
        name="reception-message-threads-list",
    ),
    path(
        "reviews/",
        ReceptionReviewsListView.as_view(),
        name="reception-reviews-list",
    ),
    path(
        "reviews/<int:review_id>/",
        ReceptionReviewDetailView.as_view(),
        name="reception-review-detail",
    ),
    path(
        "reviews/<int:review_id>/reply/",
        ReceptionReviewReplyView.as_view(),
        name="reception-review-reply",
    ),
    path(
        "reviews/<int:review_id>/compose-reply/",
        ReceptionReviewComposeReplyView.as_view(),
        name="reception-review-compose-reply",
    ),
    path(
        "reviews/<int:review_id>/guest-review/",
        ReceptionReviewGuestReviewView.as_view(),
        name="reception-review-guest-review",
    ),
    path(
        "reservations/<int:reservation_id>/reviews/",
        ReceptionReservationReviewsView.as_view(),
        name="reception-reservation-reviews",
    ),
    path(
        "reservations/<int:reservation_id>/guests/",
        ReservationGuestListCreateView.as_view(),
        name="reception-guest-list-create",
    ),
    path(
        "reservations/<int:reservation_id>/guests/<int:guest_id>/",
        ReservationGuestDetailView.as_view(),
        name="reception-guest-detail",
    ),
    path(
        "reservations/<int:reservation_id>/guests/<int:guest_id>/face-photo/",
        GuestFacePhotoView.as_view(),
        name="reception-guest-face-photo",
    ),
    path(
        "reservations/<int:reservation_id>/guests/<int:guest_id>/document-scan/",
        DocumentScanIngestView.as_view(),
        name="reception-document-scan",
    ),
    path(
        "reservations/<int:reservation_id>/guests/<int:guest_id>/document-photos/",
        DocumentPhotosUploadView.as_view(),
        name="reception-document-photos",
    ),
    path(
        "reservations/<int:reservation_id>/guests/<int:guest_id>/id-scan-samples/",
        IdScanSampleUploadView.as_view(),
        name="reception-id-scan-samples",
    ),
    path(
        "reservations/<int:reservation_id>/guests/<int:guest_id>/evisitor-submit/",
        EvisitorSubmitView.as_view(),
        name="reception-evisitor-submit",
    ),
    path(
        "calendar/blocks/",
        ReceptionCalendarBlocksView.as_view(),
        name="reception-calendar-blocks",
    ),
    path(
        "calendar/channel-ari/",
        ReceptionChannelCalendarAriView.as_view(),
        name="reception-calendar-channel-ari",
    ),
    path(
        "units/<int:unit_id>/availability/",
        ReceptionUnitAvailabilityView.as_view(),
        name="reception-unit-availability",
    ),
    path(
        "units/<int:unit_id>/block/",
        ReceptionUnitBlockCreateView.as_view(),
        name="reception-unit-block-create",
    ),
    path(
        "blocks/<int:block_id>/",
        ReceptionUnitBlockDeleteView.as_view(),
        name="reception-unit-block-delete",
    ),
    path(
        "channel/status/",
        ReceptionChannelStatusView.as_view(),
        name="reception-channel-status",
    ),
    path(
        "channel/bulk-apply/",
        ReceptionChannelBulkApplyView.as_view(),
        name="reception-channel-bulk-apply",
    ),
    path(
        "channel/full-sync/",
        ReceptionChannelFullSyncView.as_view(),
        name="reception-channel-full-sync",
    ),
    path(
        "channel/rates/",
        ReceptionChannelRatesView.as_view(),
        name="reception-channel-rates",
    ),
    path(
        "channel/rate-plans/",
        ReceptionChannelRatePlansView.as_view(),
        name="reception-channel-rate-plans",
    ),
    path(
        "channel/availability/",
        ReceptionChannelAvailabilityView.as_view(),
        name="reception-channel-availability",
    ),
]
