from django.urls import path

from apps.api.reception_calendar_block_views import (
    ReceptionCalendarBlocksView,
    ReceptionUnitBlockCreateView,
    ReceptionUnitBlockDeleteView,
)
from apps.api.reception_views import (
    DocumentPhotosUploadView,
    DocumentScanIngestView,
    EvisitorSubmitView,
    GuestFacePhotoView,
    IdScanSampleUploadView,
    ReceptionHealthView,
    ReceptionMonthlyStatisticsView,
    ReceptionSyncVersionsView,
    ReservationDetailView,
    ReservationGuestDetailView,
    ReservationGuestListCreateView,
    ReservationTimelineListView,
)

urlpatterns = [
    path("health/", ReceptionHealthView.as_view(), name="reception-health"),
    path(
        "sync-versions/",
        ReceptionSyncVersionsView.as_view(),
        name="reception-sync-versions",
    ),
    path(
        "statistics/monthly/",
        ReceptionMonthlyStatisticsView.as_view(),
        name="reception-statistics-monthly",
    ),
    path(
        "reservations/",
        ReservationTimelineListView.as_view(),
        name="reception-reservations-list",
    ),
    path(
        "reservations/<int:pk>/",
        ReservationDetailView.as_view(),
        name="reception-reservation-detail",
    ),
    path(
        "reservations/<int:reservation_id>/guests/",
        ReservationGuestListCreateView.as_view(),
        name="reception-guest-list-create",
    ),
    path(
        "reservations/<int:reservation_id>/guests/<int:guest_id>/",
        ReservationGuestDetailView.as_view(),
        name="reception-guest-detail",
    ),
    path(
        "reservations/<int:reservation_id>/guests/<int:guest_id>/face-photo/",
        GuestFacePhotoView.as_view(),
        name="reception-guest-face-photo",
    ),
    path(
        "reservations/<int:reservation_id>/guests/<int:guest_id>/document-scan/",
        DocumentScanIngestView.as_view(),
        name="reception-document-scan",
    ),
    path(
        "reservations/<int:reservation_id>/guests/<int:guest_id>/document-photos/",
        DocumentPhotosUploadView.as_view(),
        name="reception-document-photos",
    ),
    path(
        "reservations/<int:reservation_id>/guests/<int:guest_id>/id-scan-samples/",
        IdScanSampleUploadView.as_view(),
        name="reception-id-scan-samples",
    ),
    path(
        "reservations/<int:reservation_id>/guests/<int:guest_id>/evisitor-submit/",
        EvisitorSubmitView.as_view(),
        name="reception-evisitor-submit",
    ),
    path(
        "calendar/blocks/",
        ReceptionCalendarBlocksView.as_view(),
        name="reception-calendar-blocks",
    ),
    path(
        "units/<int:unit_id>/block/",
        ReceptionUnitBlockCreateView.as_view(),
        name="reception-unit-block-create",
    ),
    path(
        "blocks/<int:block_id>/",
        ReceptionUnitBlockDeleteView.as_view(),
        name="reception-unit-block-delete",
    ),
]
