from django.urls import path

from apps.api.reception_availability_views import ReceptionUnitAvailabilityView
from apps.api.reception_calendar_block_views import (
    ReceptionCalendarBlocksView,
    ReceptionUnitBlockCreateView,
    ReceptionUnitBlockDeleteView,
)
from apps.api.reception_channex_views import (
    ReceptionChannelAvailabilityView,
    ReceptionChannelBulkApplyView,
    ReceptionChannelCalendarAriView,
    ReceptionChannelFullSyncView,
    ReceptionChannelRatePlansView,
    ReceptionChannelRatesView,
    ReceptionChannelStatusView,
    ReceptionReservationCreateView,
)
from apps.api.reception_views import (
    BookingPdfImportView,
    DocumentPhotosUploadView,
    DocumentScanIngestView,
    EvisitorSubmitView,
    GuestFacePhotoView,
    IdScanSampleUploadView,
    ReceptionHealthView,
    ReceptionMonthlyStatisticsView,
    ReceptionSyncVersionsView,
    ReservationConfirmationPdfView,
    ReservationDetailView,
    ReservationGuestDetailView,
    ReservationGuestListCreateView,
    ReservationTimelineListView,
)

urlpatterns = [
    path("health/", ReceptionHealthView.as_view(), name="reception-health"),
    path(
        "sync-versions/",
        ReceptionSyncVersionsView.as_view(),
        name="reception-sync-versions",
    ),
    path(
        "statistics/monthly/",
        ReceptionMonthlyStatisticsView.as_view(),
        name="reception-statistics-monthly",
    ),
    path(
        "reservations/",
        ReservationTimelineListView.as_view(),
        name="reception-reservations-list",
    ),
    path(
        "reservations/create/",
        ReceptionReservationCreateView.as_view(),
        name="reception-reservation-create",
    ),
    path(
        "reservations/import-pdf/",
        BookingPdfImportView.as_view(),
        name="reception-reservation-import-pdf",
    ),
    path(
        "reservations/<int:pk>/confirmation-pdf/",
        ReservationConfirmationPdfView.as_view(),
        name="reception-reservation-confirmation-pdf",
    ),
    path(
        "reservations/<int:pk>/",
        ReservationDetailView.as_view(),
        name="reception-reservation-detail",
    ),
    path(
        "reservations/<int:reservation_id>/guests/",
        ReservationGuestListCreateView.as_view(),
        name="reception-guest-list-create",
    ),
    path(
        "reservations/<int:reservation_id>/guests/<int:guest_id>/",
        ReservationGuestDetailView.as_view(),
        name="reception-guest-detail",
    ),
    path(
        "reservations/<int:reservation_id>/guests/<int:guest_id>/face-photo/",
        GuestFacePhotoView.as_view(),
        name="reception-guest-face-photo",
    ),
    path(
        "reservations/<int:reservation_id>/guests/<int:guest_id>/document-scan/",
        DocumentScanIngestView.as_view(),
        name="reception-document-scan",
    ),
    path(
        "reservations/<int:reservation_id>/guests/<int:guest_id>/document-photos/",
        DocumentPhotosUploadView.as_view(),
        name="reception-document-photos",
    ),
    path(
        "reservations/<int:reservation_id>/guests/<int:guest_id>/id-scan-samples/",
        IdScanSampleUploadView.as_view(),
        name="reception-id-scan-samples",
    ),
    path(
        "reservations/<int:reservation_id>/guests/<int:guest_id>/evisitor-submit/",
        EvisitorSubmitView.as_view(),
        name="reception-evisitor-submit",
    ),
    path(
        "calendar/blocks/",
        ReceptionCalendarBlocksView.as_view(),
        name="reception-calendar-blocks",
    ),
    path(
        "calendar/channel-ari/",
        ReceptionChannelCalendarAriView.as_view(),
        name="reception-calendar-channel-ari",
    ),
    path(
        "units/<int:unit_id>/availability/",
        ReceptionUnitAvailabilityView.as_view(),
        name="reception-unit-availability",
    ),
    path(
        "units/<int:unit_id>/block/",
        ReceptionUnitBlockCreateView.as_view(),
        name="reception-unit-block-create",
    ),
    path(
        "blocks/<int:block_id>/",
        ReceptionUnitBlockDeleteView.as_view(),
        name="reception-unit-block-delete",
    ),
    path(
        "channel/status/",
        ReceptionChannelStatusView.as_view(),
        name="reception-channel-status",
    ),
    path(
        "channel/bulk-apply/",
        ReceptionChannelBulkApplyView.as_view(),
        name="reception-channel-bulk-apply",
    ),
    path(
        "channel/full-sync/",
        ReceptionChannelFullSyncView.as_view(),
        name="reception-channel-full-sync",
    ),
    path(
        "channel/rates/",
        ReceptionChannelRatesView.as_view(),
        name="reception-channel-rates",
    ),
    path(
        "channel/rate-plans/",
        ReceptionChannelRatePlansView.as_view(),
        name="reception-channel-rate-plans",
    ),
    path(
        "channel/availability/",
        ReceptionChannelAvailabilityView.as_view(),
        name="reception-channel-availability",
    ),
]
