# Generated by Django 5.1.15 on 2026-06-04 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0012_reservation_status_no_show'),
        ('tenants', '0013_tenantreceptionsettings_remove_auto_checkout_clock'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestMessageDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(choices=[('checkin', 'Check-in'), ('reply', 'Reply'), ('custom', 'Custom')], max_length=16)),
                ('hint', models.TextField(blank=True, default='')),
                ('llm_body_text', models.TextField(blank=True, default='')),
                ('final_body_text', models.TextField(blank=True, default='')),
                ('language', models.CharField(blank=True, default='', max_length=8)),
                ('channel', models.CharField(blank=True, choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], default='', max_length=16)),
                ('llm_model', models.CharField(blank=True, default='', max_length=64)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('api_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_message_drafts', to='tenants.apiapplication')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_message_drafts', to='reservations.reservation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Guest message draft',
                'verbose_name_plural': 'Guest message drafts',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GuestOutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=16)),
                ('body_text', models.TextField()),
                ('status', models.CharField(choices=[('handoff_whatsapp', 'WhatsApp handoff'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], max_length=32)),
                ('to_email', models.EmailField(blank=True, default='', max_length=254)),
                ('to_phone', models.CharField(blank=True, default='', max_length=64)),
                ('wa_me_url', models.URLField(blank=True, default='', max_length=512)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_outbound_messages', to='tenants.apiapplication')),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_messages', to='communications.guestmessagedraft')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_outbound_messages', to='reservations.reservation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Guest outbound message',
                'verbose_name_plural': 'Guest outbound messages',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='guestmessagedraft',
            index=models.Index(fields=['tenant', 'reservation', '-created_at'], name='communicati_tenant__3fe8cd_idx'),
        ),
        migrations.AddIndex(
            model_name='guestoutboundmessage',
            index=models.Index(fields=['tenant', 'reservation', '-created_at'], name='communicati_tenant__3c5617_idx'),
        ),
        migrations.AddIndex(
            model_name='guestoutboundmessage',
            index=models.Index(fields=['draft'], name='communicati_draft_i_b9b0e2_idx'),
        ),
    ]
