# Generated by Django 5.1.15 on 2026-06-06 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0004_guest_message_thread_state_and_translation"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="guestmessagethreadstate",
            new_name="communicati_tenant__8f3bf9_idx",
            old_name="communicati_tenant__a8b2c1_idx",
        ),
        migrations.RenameIndex(
            model_name="guestmessagetranslation",
            new_name="communicati_tenant__d853ca_idx",
            old_name="communicati_tenant__d4e5f6_idx",
        ),
    ]
