"""ISO 3166-1 alpha-2 country names in Croatian for invoice PDFs."""

from __future__ import annotations

_COUNTRY_NAMES_HR: dict[str, str] = {
    "AD": "Andora",
    "AE": "Ujedinjeni Arapski Emirati",
    "AF": "Afganistan",
    "AG": "Antigva i Barbuda",
    "AI": "Angvila",
    "AL": "Albanija",
    "AM": "Armenija",
    "AO": "Angola",
    "AR": "Argentina",
    "AT": "Austrija",
    "AU": "Australija",
    "AW": "Aruba",
    "AZ": "Azerbajdžan",
    "BA": "Bosna i Hercegovina",
    "BB": "Barbados",
    "BD": "Bangladeš",
    "BE": "Belgija",
    "BF": "Burkina Faso",
    "BG": "Bugarska",
    "BH": "Bahrein",
    "BI": "Burundi",
    "BJ": "Benin",
    "BN": "Brunej",
    "BO": "Bolivija",
    "BR": "Brazil",
    "BS": "Bahami",
    "BT": "Butan",
    "BW": "Bocvana",
    "BY": "Bjelorusija",
    "BZ": "Belize",
    "CA": "Kanada",
    "CD": "Demokratska Republika Kongo",
    "CF": "Centralnoafrička Republika",
    "CG": "Kongo",
    "CH": "Švicarska",
    "CI": "Obala Bjelokosti",
    "CL": "Čile",
    "CM": "Kamerun",
    "CN": "Kina",
    "CO": "Kolumbija",
    "CR": "Kostarika",
    "CU": "Kuba",
    "CV": "Zelenortski Otoci",
    "CY": "Cipar",
    "CZ": "Češka",
    "DE": "Njemačka",
    "DJ": "Džibuti",
    "DK": "Danska",
    "DM": "Dominika",
    "DO": "Dominikanska Republika",
    "DZ": "Alžir",
    "EC": "Ekvador",
    "EE": "Estonija",
    "EG": "Egipat",
    "ER": "Eritreja",
    "ES": "Španjolska",
    "ET": "Etiopija",
    "FI": "Finska",
    "FJ": "Fidži",
    "FR": "Francuska",
    "GA": "Gabon",
    "GB": "Ujedinjeno Kraljevstvo",
    "GD": "Grenada",
    "GE": "Gruzija",
    "GH": "Gana",
    "GM": "Gambija",
    "GN": "Gvineja",
    "GQ": "Ekvatorska Gvineja",
    "GR": "Grčka",
    "GT": "Gvatemala",
    "GW": "Gvineja Bisau",
    "GY": "Gvajana",
    "HK": "Hong Kong",
    "HN": "Honduras",
    "HR": "Hrvatska",
    "HT": "Haiti",
    "HU": "Mađarska",
    "ID": "Indonezija",
    "IE": "Irska",
    "IL": "Izrael",
    "IN": "Indija",
    "IQ": "Irak",
    "IR": "Iran",
    "IS": "Island",
    "IT": "Italija",
    "JM": "Jamajka",
    "JO": "Jordan",
    "JP": "Japan",
    "KE": "Kenija",
    "KG": "Kirgistan",
    "KH": "Kambodža",
    "KM": "Komori",
    "KN": "Sveti Kristofor i Nevis",
    "KP": "Sjeverna Koreja",
    "KR": "Južna Koreja",
    "KW": "Kuvajt",
    "KZ": "Kazahstan",
    "LA": "Laos",
    "LB": "Libanon",
    "LC": "Sveta Lucija",
    "LI": "Lihtenštajn",
    "LK": "Šri Lanka",
    "LR": "Liberija",
    "LS": "Lesoto",
    "LT": "Litva",
    "LU": "Luksemburg",
    "LV": "Latvija",
    "LY": "Libija",
    "MA": "Maroko",
    "MC": "Monako",
    "MD": "Moldavija",
    "ME": "Crna Gora",
    "MG": "Madagaskar",
    "MK": "Sjeverna Makedonija",
    "ML": "Mali",
    "MM": "Mjanmar",
    "MN": "Mongolija",
    "MO": "Makao",
    "MR": "Mauritanija",
    "MT": "Malta",
    "MU": "Mauricijus",
    "MV": "Maldivi",
    "MW": "Malavi",
    "MX": "Meksiko",
    "MY": "Malezija",
    "MZ": "Mozambik",
    "NA": "Namibija",
    "NE": "Niger",
    "NG": "Nigerija",
    "NI": "Nikaragva",
    "NL": "Nizozemska",
    "NO": "Norveška",
    "NP": "Nepal",
    "NZ": "Novi Zeland",
    "OM": "Oman",
    "PA": "Panama",
    "PE": "Peru",
    "PG": "Papua Nova Gvineja",
    "PH": "Filipini",
    "PK": "Pakistan",
    "PL": "Poljska",
    "PT": "Portugal",
    "PY": "Paragvaj",
    "QA": "Katar",
    "RO": "Rumunjska",
    "RS": "Srbija",
    "RU": "Rusija",
    "RW": "Ruanda",
    "SA": "Saudijska Arabija",
    "SC": "Sejšeli",
    "SD": "Sudan",
    "SE": "Švedska",
    "SG": "Singapur",
    "SI": "Slovenija",
    "SK": "Slovačka",
    "SL": "Sijera Leone",
    "SM": "San Marino",
    "SN": "Senegal",
    "SO": "Somalija",
    "SR": "Surinam",
    "SS": "Južni Sudan",
    "SV": "Salvador",
    "SY": "Sirija",
    "SZ": "Esvatini",
    "TD": "Čad",
    "TG": "Togo",
    "TH": "Tajland",
    "TJ": "Tadžikistan",
    "TL": "Istočni Timor",
    "TM": "Turkmenistan",
    "TN": "Tunis",
    "TR": "Turska",
    "TT": "Trinidad i Tobago",
    "TW": "Tajvan",
    "TZ": "Tanzanija",
    "UA": "Ukrajina",
    "UG": "Uganda",
    "US": "Sjedinjene Američke Države",
    "UY": "Urugvaj",
    "UZ": "Uzbekistan",
    "VA": "Vatikanski Grad",
    "VE": "Venezuela",
    "VN": "Vijetnam",
    "VU": "Vanuatu",
    "XK": "Kosovo",
    "YE": "Jemen",
    "ZA": "Južnoafrička Republika",
    "ZM": "Zambija",
    "ZW": "Zimbabve",
}


def country_display_name_hr(raw: str) -> str:
    value = (raw or "").strip()
    if not value:
        return ""
    if len(value) == 2 and value.isalpha():
        return _COUNTRY_NAMES_HR.get(value.upper(), value.upper())
    return value
